package b4a.example;

import anywheresoftware.b4a.BA;
import anywheresoftware.b4a.pc.*;

public class main_subs_0 {


public static RemoteObject  _activity_create(RemoteObject _firsttime) throws Exception{
try {
		Debug.PushSubsStack("Activity_Create (main) ","main",0,main.mostCurrent.activityBA,main.mostCurrent,316);
if (RapidSub.canDelegate("activity_create")) { return b4a.example.main.remoteMe.runUserSub(false, "main","activity_create", _firsttime);}
RemoteObject _gradient = RemoteObject.declareNull("anywheresoftware.b4a.objects.drawable.GradientDrawable");
RemoteObject _barpanel = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
RemoteObject _sales = null;
Debug.locals.put("FirstTime", _firsttime);
 BA.debugLineNum = 316;BA.debugLine="Sub Activity_Create(FirstTime As Boolean)";
Debug.ShouldStop(134217728);
 BA.debugLineNum = 317;BA.debugLine="Activity.LoadLayout(\"Layout\")";
Debug.ShouldStop(268435456);
main.mostCurrent._activity.runMethodAndSync(false,"LoadLayout",(Object)(RemoteObject.createImmutable("Layout")),main.mostCurrent.activityBA);
 BA.debugLineNum = 318;BA.debugLine="Label1.Text = Label1.Text.ToUpperCase";
Debug.ShouldStop(536870912);
main.mostCurrent._label1.runMethod(true,"setText",BA.ObjectToCharSequence(main.mostCurrent._label1.runMethod(true,"getText").runMethod(true,"toUpperCase")));
 BA.debugLineNum = 319;BA.debugLine="Label1.Typeface = Typeface.MONOSPACE";
Debug.ShouldStop(1073741824);
main.mostCurrent._label1.runMethod(false,"setTypeface",main.mostCurrent.__c.getField(false,"Typeface").getField(false,"MONOSPACE"));
 BA.debugLineNum = 320;BA.debugLine="ScrollView1.Panel.Color = Colors.ARGB(255, 251, 2";
Debug.ShouldStop(-2147483648);
main.mostCurrent._scrollview1.runMethod(false,"getPanel").runVoidMethod ("setColor",main.mostCurrent.__c.getField(false,"Colors").runMethod(true,"ARGB",(Object)(BA.numberCast(int.class, 255)),(Object)(BA.numberCast(int.class, 251)),(Object)(BA.numberCast(int.class, 251)),(Object)(BA.numberCast(int.class, 251))));
 BA.debugLineNum = 321;BA.debugLine="Dim gradient As GradientDrawable";
Debug.ShouldStop(1);
_gradient = RemoteObject.createNew ("anywheresoftware.b4a.objects.drawable.GradientDrawable");Debug.locals.put("gradient", _gradient);
 BA.debugLineNum = 322;BA.debugLine="gradient.Initialize(\"RIGHT_LEFT\", Array As Int(Co";
Debug.ShouldStop(2);
_gradient.runVoidMethod ("Initialize",(Object)(BA.getEnumFromString(BA.getDeviceClass("android.graphics.drawable.GradientDrawable.Orientation"),"RIGHT_LEFT")),(Object)(RemoteObject.createNewArray("int",new int[] {2},new Object[] {main.mostCurrent.__c.getField(false,"Colors").runMethod(true,"RGB",(Object)(BA.numberCast(int.class, 225)),(Object)(BA.numberCast(int.class, 218)),(Object)(BA.numberCast(int.class, 218))),main.mostCurrent.__c.getField(false,"Colors").runMethod(true,"RGB",(Object)(BA.numberCast(int.class, 189)),(Object)(BA.numberCast(int.class, 202)),(Object)(BA.numberCast(int.class, 217)))})));
 BA.debugLineNum = 324;BA.debugLine="ScrollView1.Background = gradient";
Debug.ShouldStop(8);
main.mostCurrent._scrollview1.runMethod(false,"setBackground",(_gradient.getObject()));
 BA.debugLineNum = 325;BA.debugLine="Dim gradient As GradientDrawable";
Debug.ShouldStop(16);
_gradient = RemoteObject.createNew ("anywheresoftware.b4a.objects.drawable.GradientDrawable");Debug.locals.put("gradient", _gradient);
 BA.debugLineNum = 326;BA.debugLine="gradient.Initialize(\"RIGHT_LEFT\", Array As Int(Co";
Debug.ShouldStop(32);
_gradient.runVoidMethod ("Initialize",(Object)(BA.getEnumFromString(BA.getDeviceClass("android.graphics.drawable.GradientDrawable.Orientation"),"RIGHT_LEFT")),(Object)(RemoteObject.createNewArray("int",new int[] {2},new Object[] {main.mostCurrent.__c.getField(false,"Colors").runMethod(true,"ARGB",(Object)(BA.numberCast(int.class, 255)),(Object)(BA.numberCast(int.class, 185)),(Object)(BA.numberCast(int.class, 46)),(Object)(BA.numberCast(int.class, 52))),main.mostCurrent.__c.getField(false,"Colors").runMethod(true,"ARGB",(Object)(BA.numberCast(int.class, 255)),(Object)(BA.numberCast(int.class, 61)),(Object)(BA.numberCast(int.class, 12)),(Object)(BA.numberCast(int.class, 2)))})));
 BA.debugLineNum = 328;BA.debugLine="Panel2.Background = gradient";
Debug.ShouldStop(128);
main.mostCurrent._panel2.runMethod(false,"setBackground",(_gradient.getObject()));
 BA.debugLineNum = 333;BA.debugLine="Log(Activity.Width)";
Debug.ShouldStop(4096);
main.mostCurrent.__c.runVoidMethod ("LogImpl","0262161",BA.NumberToString(main.mostCurrent._activity.runMethod(true,"getWidth")),0);
 BA.debugLineNum = 334;BA.debugLine="Dim barPanel As Panel";
Debug.ShouldStop(8192);
_barpanel = RemoteObject.createNew ("anywheresoftware.b4a.objects.PanelWrapper");Debug.locals.put("barPanel", _barpanel);
 BA.debugLineNum = 335;BA.debugLine="barPanel.Initialize(\"\")";
Debug.ShouldStop(16384);
_barpanel.runVoidMethod ("Initialize",main.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("")));
 BA.debugLineNum = 336;BA.debugLine="Dim sales() As Int";
Debug.ShouldStop(32768);
_sales = RemoteObject.createNewArray ("int", new int[] {0}, new Object[]{});Debug.locals.put("sales", _sales);
 BA.debugLineNum = 337;BA.debugLine="sales = Array As Int(100, 2000, 1500, 3000, 4000,";
Debug.ShouldStop(65536);
_sales = RemoteObject.createNewArray("int",new int[] {7},new Object[] {BA.numberCast(int.class, 100),BA.numberCast(int.class, 2000),BA.numberCast(int.class, 1500),BA.numberCast(int.class, 3000),BA.numberCast(int.class, 4000),BA.numberCast(int.class, 50000),BA.numberCast(int.class, 60000)});Debug.locals.put("sales", _sales);
 BA.debugLineNum = 338;BA.debugLine="Panel1.AddView(barPanel,25dip,Panel2.Height,Activ";
Debug.ShouldStop(131072);
main.mostCurrent._panel1.runVoidMethod ("AddView",(Object)((_barpanel.getObject())),(Object)(main.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 25)))),(Object)(main.mostCurrent._panel2.runMethod(true,"getHeight")),(Object)(RemoteObject.solve(new RemoteObject[] {main.mostCurrent._activity.runMethod(true,"getWidth"),main.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 50)))}, "-",1, 1)),(Object)(main.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 300)))));
 BA.debugLineNum = 339;BA.debugLine="barGraph.Initialize(Activity,barPanel,sales,10000";
Debug.ShouldStop(262144);
main.mostCurrent._bargraph.runClassMethod (b4a.example.bargraph.class, "_initialize" /*RemoteObject*/ ,main.mostCurrent.activityBA,(Object)(main.mostCurrent._activity),(Object)(_barpanel),(Object)(_sales),(Object)(BA.numberCast(int.class, 100000)));
 BA.debugLineNum = 340;BA.debugLine="End Sub";
Debug.ShouldStop(524288);
return RemoteObject.createImmutable("");
}
catch (Exception e) {
			throw Debug.ErrorCaught(e);
		} 
finally {
			Debug.PopSubsStack();
		}}
public static RemoteObject  _activity_pause(RemoteObject _userclosed) throws Exception{
try {
		Debug.PushSubsStack("Activity_Pause (main) ","main",0,main.mostCurrent.activityBA,main.mostCurrent,346);
if (RapidSub.canDelegate("activity_pause")) { return b4a.example.main.remoteMe.runUserSub(false, "main","activity_pause", _userclosed);}
Debug.locals.put("UserClosed", _userclosed);
 BA.debugLineNum = 346;BA.debugLine="Sub Activity_Pause (UserClosed As Boolean)";
Debug.ShouldStop(33554432);
 BA.debugLineNum = 348;BA.debugLine="End Sub";
Debug.ShouldStop(134217728);
return RemoteObject.createImmutable("");
}
catch (Exception e) {
			throw Debug.ErrorCaught(e);
		} 
finally {
			Debug.PopSubsStack();
		}}
public static RemoteObject  _activity_resume() throws Exception{
try {
		Debug.PushSubsStack("Activity_Resume (main) ","main",0,main.mostCurrent.activityBA,main.mostCurrent,342);
if (RapidSub.canDelegate("activity_resume")) { return b4a.example.main.remoteMe.runUserSub(false, "main","activity_resume");}
 BA.debugLineNum = 342;BA.debugLine="Sub Activity_Resume";
Debug.ShouldStop(2097152);
 BA.debugLineNum = 344;BA.debugLine="End Sub";
Debug.ShouldStop(8388608);
return RemoteObject.createImmutable("");
}
catch (Exception e) {
			throw Debug.ErrorCaught(e);
		} 
finally {
			Debug.PopSubsStack();
		}}
public static RemoteObject  _globals() throws Exception{
 //BA.debugLineNum = 22;BA.debugLine="Sub Globals";
 //BA.debugLineNum = 24;BA.debugLine="Private ScrollView1 As ScrollView";
main.mostCurrent._scrollview1 = RemoteObject.createNew ("anywheresoftware.b4a.objects.ScrollViewWrapper");
 //BA.debugLineNum = 25;BA.debugLine="Dim PHPURL As String = \"https://192.168.8.141/Com";
main.mostCurrent._phpurl = BA.ObjectToString("https://192.168.8.141/Company/fetch.php?action=get_company_list");
 //BA.debugLineNum = 26;BA.debugLine="Dim TableDetails As List";
main.mostCurrent._tabledetails = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.List");
 //BA.debugLineNum = 28;BA.debugLine="Private Button1 As Button";
main.mostCurrent._button1 = RemoteObject.createNew ("anywheresoftware.b4a.objects.ButtonWrapper");
 //BA.debugLineNum = 29;BA.debugLine="Private navigate As Label";
main.mostCurrent._navigate = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");
 //BA.debugLineNum = 30;BA.debugLine="Dim titleFontSize As Int = 4.5%y";
main._titlefontsize = main.mostCurrent.__c.runMethod(true,"PerYToCurrent",(Object)(BA.numberCast(float.class, 4.5)),main.mostCurrent.activityBA);
 //BA.debugLineNum = 31;BA.debugLine="Dim primaryFontSize As Int = 1.6%y";
main._primaryfontsize = main.mostCurrent.__c.runMethod(true,"PerYToCurrent",(Object)(BA.numberCast(float.class, 1.6)),main.mostCurrent.activityBA);
 //BA.debugLineNum = 32;BA.debugLine="Dim secondaryFontSize As Int = 1%y";
main._secondaryfontsize = main.mostCurrent.__c.runMethod(true,"PerYToCurrent",(Object)(BA.numberCast(float.class, 1)),main.mostCurrent.activityBA);
 //BA.debugLineNum = 33;BA.debugLine="Private Panel1 As Panel";
main.mostCurrent._panel1 = RemoteObject.createNew ("anywheresoftware.b4a.objects.PanelWrapper");
 //BA.debugLineNum = 34;BA.debugLine="Private Label1 As Label";
main.mostCurrent._label1 = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");
 //BA.debugLineNum = 35;BA.debugLine="Private Panel2 As Panel";
main.mostCurrent._panel2 = RemoteObject.createNew ("anywheresoftware.b4a.objects.PanelWrapper");
 //BA.debugLineNum = 36;BA.debugLine="Dim barGraph As barGraph";
main.mostCurrent._bargraph = RemoteObject.createNew ("b4a.example.bargraph");
 //BA.debugLineNum = 38;BA.debugLine="End Sub";
return RemoteObject.createImmutable("");
}
public static RemoteObject  _jobdone(RemoteObject _job) throws Exception{
try {
		Debug.PushSubsStack("JobDone (main) ","main",0,main.mostCurrent.activityBA,main.mostCurrent,47);
if (RapidSub.canDelegate("jobdone")) { return b4a.example.main.remoteMe.runUserSub(false, "main","jobdone", _job);}
RemoteObject _scrollheight = RemoteObject.createImmutable(0);
RemoteObject _parser = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.JSONParser");
RemoteObject _numcolumns = RemoteObject.createImmutable(0);
RemoteObject _pnlwidth = RemoteObject.createImmutable(0);
RemoteObject _pnlheight = RemoteObject.createImmutable(0);
RemoteObject _padding = RemoteObject.createImmutable(0);
RemoteObject _leftposition = RemoteObject.createImmutable(0);
RemoteObject _topposition = RemoteObject.createImmutable(0);
RemoteObject _count = RemoteObject.createImmutable(0);
RemoteObject _record = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.Map");
RemoteObject _name = RemoteObject.createImmutable("");
RemoteObject _company_id = RemoteObject.createImmutable(0);
RemoteObject _total_count = RemoteObject.createImmutable(0);
RemoteObject _total_pos = RemoteObject.createImmutable(0);
RemoteObject _totalpur1 = RemoteObject.createImmutable("");
RemoteObject _totalpur2 = RemoteObject.createImmutable("");
RemoteObject _totalpur3 = RemoteObject.createImmutable("");
RemoteObject _totalsales1 = RemoteObject.createImmutable("");
RemoteObject _totalsales2 = RemoteObject.createImmutable("");
RemoteObject _totalsales3 = RemoteObject.createImmutable("");
RemoteObject _panel = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
RemoteObject _label17 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _myimage = RemoteObject.declareNull("anywheresoftware.b4a.objects.drawable.CanvasWrapper.BitmapWrapper");
RemoteObject _resizedimage = RemoteObject.declareNull("anywheresoftware.b4a.objects.drawable.CanvasWrapper.BitmapWrapper");
RemoteObject _imgview = RemoteObject.declareNull("anywheresoftware.b4a.objects.ImageViewWrapper");
RemoteObject _panelwidth = RemoteObject.createImmutable(0);
RemoteObject _labelheight = RemoteObject.createImmutable(0);
RemoteObject _purchase1 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _purchase1label = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _purchase2 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _purchase2label = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _purchase3 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _purchase3label = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _sale1 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _sale1label = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _sale2 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _sale2label = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _sale3 = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _sale3label = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _totalstore = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _totalstorelabel = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _totalpos = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _totalposlabel = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _cd = RemoteObject.declareNull("anywheresoftware.b4a.objects.drawable.ColorDrawable");
Debug.locals.put("job", _job);
 BA.debugLineNum = 47;BA.debugLine="Sub JobDone(job As HttpJob)";
Debug.ShouldStop(16384);
 BA.debugLineNum = 48;BA.debugLine="ProgressDialogHide";
Debug.ShouldStop(32768);
main.mostCurrent.__c.runVoidMethod ("ProgressDialogHide");
 BA.debugLineNum = 49;BA.debugLine="Dim scrollHeight As Int = 0";
Debug.ShouldStop(65536);
_scrollheight = BA.numberCast(int.class, 0);Debug.locals.put("scrollHeight", _scrollheight);Debug.locals.put("scrollHeight", _scrollheight);
 BA.debugLineNum = 50;BA.debugLine="If job.Success = True Then";
Debug.ShouldStop(131072);
if (RemoteObject.solveBoolean("=",_job.getField(true,"_success" /*RemoteObject*/ ),main.mostCurrent.__c.getField(true,"True"))) { 
 BA.debugLineNum = 51;BA.debugLine="Try";
Debug.ShouldStop(262144);
try { BA.debugLineNum = 52;BA.debugLine="Dim parser As JSONParser";
Debug.ShouldStop(524288);
_parser = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.JSONParser");Debug.locals.put("parser", _parser);
 BA.debugLineNum = 53;BA.debugLine="parser.Initialize(job.GetString)";
Debug.ShouldStop(1048576);
_parser.runVoidMethod ("Initialize",(Object)(_job.runClassMethod (b4a.example.httpjob.class, "_getstring" /*RemoteObject*/ )));
 BA.debugLineNum = 54;BA.debugLine="TableDetails = parser.NextArray";
Debug.ShouldStop(2097152);
main.mostCurrent._tabledetails = _parser.runMethod(false,"NextArray");
 BA.debugLineNum = 57;BA.debugLine="Dim numColumns As Int = 2 ' Adjust based on pre";
Debug.ShouldStop(16777216);
_numcolumns = BA.numberCast(int.class, 2);Debug.locals.put("numColumns", _numcolumns);Debug.locals.put("numColumns", _numcolumns);
 BA.debugLineNum = 58;BA.debugLine="Dim pnlWidth As Int = Activity.Width - 100dip";
Debug.ShouldStop(33554432);
_pnlwidth = RemoteObject.solve(new RemoteObject[] {main.mostCurrent._activity.runMethod(true,"getWidth"),main.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 100)))}, "-",1, 1);Debug.locals.put("pnlWidth", _pnlwidth);Debug.locals.put("pnlWidth", _pnlwidth);
 BA.debugLineNum = 59;BA.debugLine="Dim pnlHeight As Int = 280dip";
Debug.ShouldStop(67108864);
_pnlheight = main.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 280)));Debug.locals.put("pnlHeight", _pnlheight);Debug.locals.put("pnlHeight", _pnlheight);
 BA.debugLineNum = 60;BA.debugLine="Dim padding As Int = 10dip";
Debug.ShouldStop(134217728);
_padding = main.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 10)));Debug.locals.put("padding", _padding);Debug.locals.put("padding", _padding);
 BA.debugLineNum = 61;BA.debugLine="Dim leftPosition As Int = 50dip";
Debug.ShouldStop(268435456);
_leftposition = main.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 50)));Debug.locals.put("leftPosition", _leftposition);Debug.locals.put("leftPosition", _leftposition);
 BA.debugLineNum = 62;BA.debugLine="Dim topPosition As Int = 77dip";
Debug.ShouldStop(536870912);
_topposition = main.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 77)));Debug.locals.put("topPosition", _topposition);Debug.locals.put("topPosition", _topposition);
 BA.debugLineNum = 63;BA.debugLine="Dim count As Int = 0 ' Track panel count";
Debug.ShouldStop(1073741824);
_count = BA.numberCast(int.class, 0);Debug.locals.put("count", _count);Debug.locals.put("count", _count);
 BA.debugLineNum = 64;BA.debugLine="If Activity.Width >= 1340 Then";
Debug.ShouldStop(-2147483648);
if (RemoteObject.solveBoolean("g",main.mostCurrent._activity.runMethod(true,"getWidth"),BA.numberCast(double.class, 1340))) { 
 BA.debugLineNum = 65;BA.debugLine="pnlWidth = 490dip";
Debug.ShouldStop(1);
_pnlwidth = main.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 490)));Debug.locals.put("pnlWidth", _pnlwidth);
 BA.debugLineNum = 66;BA.debugLine="pnlHeight = 300dip";
Debug.ShouldStop(2);
_pnlheight = main.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 300)));Debug.locals.put("pnlHeight", _pnlheight);
 BA.debugLineNum = 67;BA.debugLine="padding = 10dip";
Debug.ShouldStop(4);
_padding = main.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 10)));Debug.locals.put("padding", _padding);
 BA.debugLineNum = 68;BA.debugLine="leftPosition = 10dip";
Debug.ShouldStop(8);
_leftposition = main.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 10)));Debug.locals.put("leftPosition", _leftposition);
 };
 BA.debugLineNum = 71;BA.debugLine="For Each record As Map In TableDetails";
Debug.ShouldStop(64);
_record = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");
{
final RemoteObject group21 = main.mostCurrent._tabledetails;
final int groupLen21 = group21.runMethod(true,"getSize").<Integer>get()
;int index21 = 0;
;
for (; index21 < groupLen21;index21++){
_record = RemoteObject.declareNull("anywheresoftware.b4a.AbsObjectWrapper").runMethod(false, "ConvertToWrapper", RemoteObject.createNew("anywheresoftware.b4a.objects.collections.Map"), group21.runMethod(false,"Get",index21));Debug.locals.put("record", _record);
Debug.locals.put("record", _record);
 BA.debugLineNum = 72;BA.debugLine="Dim name As String = record.Get(\"company_name\"";
Debug.ShouldStop(128);
_name = BA.ObjectToString(_record.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("company_name")))));Debug.locals.put("name", _name);Debug.locals.put("name", _name);
 BA.debugLineNum = 73;BA.debugLine="Dim company_id As Int = record.Get(\"comId\")";
Debug.ShouldStop(256);
_company_id = BA.numberCast(int.class, _record.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("comId")))));Debug.locals.put("company_id", _company_id);Debug.locals.put("company_id", _company_id);
 BA.debugLineNum = 74;BA.debugLine="Dim total_count As Int = record.Get(\"total_cou";
Debug.ShouldStop(512);
_total_count = BA.numberCast(int.class, _record.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("total_count")))));Debug.locals.put("total_count", _total_count);Debug.locals.put("total_count", _total_count);
 BA.debugLineNum = 75;BA.debugLine="Dim total_pos As Int = record.Get(\"totalDevice";
Debug.ShouldStop(1024);
_total_pos = BA.numberCast(int.class, _record.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("totalDevices")))));Debug.locals.put("total_pos", _total_pos);Debug.locals.put("total_pos", _total_pos);
 BA.debugLineNum = 76;BA.debugLine="Dim totalPur1 As String = record.Get(\"purchase";
Debug.ShouldStop(2048);
_totalpur1 = BA.ObjectToString(_record.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("purchase_1")))));Debug.locals.put("totalPur1", _totalpur1);Debug.locals.put("totalPur1", _totalpur1);
 BA.debugLineNum = 77;BA.debugLine="Dim totalPur2 As String = record.Get(\"purchase";
Debug.ShouldStop(4096);
_totalpur2 = BA.ObjectToString(_record.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("purchase_2")))));Debug.locals.put("totalPur2", _totalpur2);Debug.locals.put("totalPur2", _totalpur2);
 BA.debugLineNum = 78;BA.debugLine="Dim totalPur3 As String = record.Get(\"purchase";
Debug.ShouldStop(8192);
_totalpur3 = BA.ObjectToString(_record.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("purchase_3")))));Debug.locals.put("totalPur3", _totalpur3);Debug.locals.put("totalPur3", _totalpur3);
 BA.debugLineNum = 79;BA.debugLine="Dim totalSales1 As String = record.Get(\"sales_";
Debug.ShouldStop(16384);
_totalsales1 = BA.ObjectToString(_record.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("sales_1")))));Debug.locals.put("totalSales1", _totalsales1);Debug.locals.put("totalSales1", _totalsales1);
 BA.debugLineNum = 80;BA.debugLine="Dim totalSales2 As String = record.Get(\"sales_";
Debug.ShouldStop(32768);
_totalsales2 = BA.ObjectToString(_record.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("sales_2")))));Debug.locals.put("totalSales2", _totalsales2);Debug.locals.put("totalSales2", _totalsales2);
 BA.debugLineNum = 81;BA.debugLine="Dim totalSales3 As String = record.Get(\"sales_";
Debug.ShouldStop(65536);
_totalsales3 = BA.ObjectToString(_record.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("sales_3")))));Debug.locals.put("totalSales3", _totalsales3);Debug.locals.put("totalSales3", _totalsales3);
 BA.debugLineNum = 84;BA.debugLine="Dim Panel As Panel";
Debug.ShouldStop(524288);
_panel = RemoteObject.createNew ("anywheresoftware.b4a.objects.PanelWrapper");Debug.locals.put("Panel", _panel);
 BA.debugLineNum = 85;BA.debugLine="Panel.Initialize(\"Panel\")";
Debug.ShouldStop(1048576);
_panel.runVoidMethod ("Initialize",main.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("Panel")));
 BA.debugLineNum = 86;BA.debugLine="ScrollView1.Panel.AddView(Panel, leftPosition,";
Debug.ShouldStop(2097152);
main.mostCurrent._scrollview1.runMethod(false,"getPanel").runVoidMethod ("AddView",(Object)((_panel.getObject())),(Object)(_leftposition),(Object)(_topposition),(Object)(_pnlwidth),(Object)(_pnlheight));
 BA.debugLineNum = 87;BA.debugLine="Panel.Color = Colors.Black";
Debug.ShouldStop(4194304);
_panel.runVoidMethod ("setColor",main.mostCurrent.__c.getField(false,"Colors").getField(true,"Black"));
 BA.debugLineNum = 90;BA.debugLine="Dim Panel2 As Panel";
Debug.ShouldStop(33554432);
main.mostCurrent._panel2 = RemoteObject.createNew ("anywheresoftware.b4a.objects.PanelWrapper");
 BA.debugLineNum = 91;BA.debugLine="Panel2.Initialize(\"Panel2\")";
Debug.ShouldStop(67108864);
main.mostCurrent._panel2.runVoidMethod ("Initialize",main.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("Panel2")));
 BA.debugLineNum = 92;BA.debugLine="Panel2.Color = Colors.Black";
Debug.ShouldStop(134217728);
main.mostCurrent._panel2.runVoidMethod ("setColor",main.mostCurrent.__c.getField(false,"Colors").getField(true,"Black"));
 BA.debugLineNum = 93;BA.debugLine="Panel2.Tag = name";
Debug.ShouldStop(268435456);
main.mostCurrent._panel2.runMethod(false,"setTag",(_name));
 BA.debugLineNum = 94;BA.debugLine="Panel2.SendToBack";
Debug.ShouldStop(536870912);
main.mostCurrent._panel2.runVoidMethod ("SendToBack");
 BA.debugLineNum = 95;BA.debugLine="Panel.AddView(Panel2, 0, 0, Panel.Width, 6%y)";
Debug.ShouldStop(1073741824);
_panel.runVoidMethod ("AddView",(Object)((main.mostCurrent._panel2.getObject())),(Object)(BA.numberCast(int.class, 0)),(Object)(BA.numberCast(int.class, 0)),(Object)(_panel.runMethod(true,"getWidth")),(Object)(main.mostCurrent.__c.runMethod(true,"PerYToCurrent",(Object)(BA.numberCast(float.class, 6)),main.mostCurrent.activityBA)));
 BA.debugLineNum = 98;BA.debugLine="Dim Label17 As Label";
Debug.ShouldStop(2);
_label17 = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("Label17", _label17);
 BA.debugLineNum = 99;BA.debugLine="Label17.Initialize(\"Label17\")";
Debug.ShouldStop(4);
_label17.runVoidMethod ("Initialize",main.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("Label17")));
 BA.debugLineNum = 100;BA.debugLine="Label17.Text = name";
Debug.ShouldStop(8);
_label17.runMethod(true,"setText",BA.ObjectToCharSequence(_name));
 BA.debugLineNum = 101;BA.debugLine="Label17.Tag = company_id";
Debug.ShouldStop(16);
_label17.runMethod(false,"setTag",(_company_id));
 BA.debugLineNum = 102;BA.debugLine="Label17.TextSize = 18";
Debug.ShouldStop(32);
_label17.runMethod(true,"setTextSize",BA.numberCast(float.class, 18));
 BA.debugLineNum = 103;BA.debugLine="Label17.TextColor = Colors.White";
Debug.ShouldStop(64);
_label17.runMethod(true,"setTextColor",main.mostCurrent.__c.getField(false,"Colors").getField(true,"White"));
 BA.debugLineNum = 104;BA.debugLine="Label17.Gravity = Gravity.CENTER_VERTICAL";
Debug.ShouldStop(128);
_label17.runMethod(true,"setGravity",main.mostCurrent.__c.getField(false,"Gravity").getField(true,"CENTER_VERTICAL"));
 BA.debugLineNum = 105;BA.debugLine="Label17.Typeface = Typeface.MONOSPACE";
Debug.ShouldStop(256);
_label17.runMethod(false,"setTypeface",main.mostCurrent.__c.getField(false,"Typeface").getField(false,"MONOSPACE"));
 BA.debugLineNum = 106;BA.debugLine="Panel2.AddView(Label17, 10dip, 0dip, Panel2.Wi";
Debug.ShouldStop(512);
main.mostCurrent._panel2.runVoidMethod ("AddView",(Object)((_label17.getObject())),(Object)(main.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 10)))),(Object)(main.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 0)))),(Object)(main.mostCurrent._panel2.runMethod(true,"getWidth")),(Object)(main.mostCurrent._panel2.runMethod(true,"getHeight")));
 BA.debugLineNum = 108;BA.debugLine="Dim myImage As Bitmap";
Debug.ShouldStop(2048);
_myimage = RemoteObject.createNew ("anywheresoftware.b4a.objects.drawable.CanvasWrapper.BitmapWrapper");Debug.locals.put("myImage", _myimage);
 BA.debugLineNum = 109;BA.debugLine="myImage = LoadBitmap(File.DirAssets, \"arrows-r";
Debug.ShouldStop(4096);
_myimage = main.mostCurrent.__c.runMethod(false,"LoadBitmap",(Object)(main.mostCurrent.__c.getField(false,"File").runMethod(true,"getDirAssets")),(Object)(RemoteObject.createImmutable("arrows-removebg-preview.png")));Debug.locals.put("myImage", _myimage);
 BA.debugLineNum = 110;BA.debugLine="If myImage.IsInitialized Then";
Debug.ShouldStop(8192);
if (_myimage.runMethod(true,"IsInitialized").<Boolean>get().booleanValue()) { 
 BA.debugLineNum = 111;BA.debugLine="Dim resizedImage As Bitmap = myImage.Resize(D";
Debug.ShouldStop(16384);
_resizedimage = RemoteObject.createNew ("anywheresoftware.b4a.objects.drawable.CanvasWrapper.BitmapWrapper");
_resizedimage = _myimage.runMethod(false,"Resize",(Object)(BA.numberCast(float.class, main.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(main.mostCurrent.__c.runMethod(true,"PerXToCurrent",(Object)(BA.numberCast(float.class, 4.5)),main.mostCurrent.activityBA))))),(Object)(BA.numberCast(float.class, RemoteObject.solve(new RemoteObject[] {_myimage.runMethod(true,"getHeight"),main.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(main.mostCurrent.__c.runMethod(true,"PerYToCurrent",(Object)(BA.numberCast(float.class, 2)),main.mostCurrent.activityBA))),_myimage.runMethod(true,"getWidth")}, "*/",0, 0))),(Object)(main.mostCurrent.__c.getField(true,"True")));Debug.locals.put("resizedImage", _resizedimage);Debug.locals.put("resizedImage", _resizedimage);
 BA.debugLineNum = 112;BA.debugLine="Dim imgView As ImageView";
Debug.ShouldStop(32768);
_imgview = RemoteObject.createNew ("anywheresoftware.b4a.objects.ImageViewWrapper");Debug.locals.put("imgView", _imgview);
 BA.debugLineNum = 113;BA.debugLine="imgView.Initialize(\"\")";
Debug.ShouldStop(65536);
_imgview.runVoidMethod ("Initialize",main.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("")));
 BA.debugLineNum = 114;BA.debugLine="imgView.Bitmap = resizedImage";
Debug.ShouldStop(131072);
_imgview.runMethod(false,"setBitmap",(_resizedimage.getObject()));
 BA.debugLineNum = 115;BA.debugLine="Panel2.AddView(imgView, Panel2.Width - 8%x, 0";
Debug.ShouldStop(262144);
main.mostCurrent._panel2.runVoidMethod ("AddView",(Object)((_imgview.getObject())),(Object)(RemoteObject.solve(new RemoteObject[] {main.mostCurrent._panel2.runMethod(true,"getWidth"),main.mostCurrent.__c.runMethod(true,"PerXToCurrent",(Object)(BA.numberCast(float.class, 8)),main.mostCurrent.activityBA)}, "-",1, 1)),(Object)(main.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 0)))),(Object)(main.mostCurrent.__c.runMethod(true,"PerXToCurrent",(Object)(BA.numberCast(float.class, 10)),main.mostCurrent.activityBA)),(Object)(main.mostCurrent._panel2.runMethod(true,"getHeight")));
 }else {
 BA.debugLineNum = 117;BA.debugLine="Log(\"Error loading image\")";
Debug.ShouldStop(1048576);
main.mostCurrent.__c.runVoidMethod ("LogImpl","0196678",RemoteObject.createImmutable("Error loading image"),0);
 };
 BA.debugLineNum = 120;BA.debugLine="Dim panelWidth As Int = Panel.Width /3";
Debug.ShouldStop(8388608);
_panelwidth = BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {_panel.runMethod(true,"getWidth"),RemoteObject.createImmutable(3)}, "/",0, 0));Debug.locals.put("panelWidth", _panelwidth);Debug.locals.put("panelWidth", _panelwidth);
 BA.debugLineNum = 121;BA.debugLine="Dim padding As Int = 10dip";
Debug.ShouldStop(16777216);
_padding = main.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 10)));Debug.locals.put("padding", _padding);Debug.locals.put("padding", _padding);
 BA.debugLineNum = 122;BA.debugLine="Dim labelheight As Int = 35dip";
Debug.ShouldStop(33554432);
_labelheight = main.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 35)));Debug.locals.put("labelheight", _labelheight);Debug.locals.put("labelheight", _labelheight);
 BA.debugLineNum = 124;BA.debugLine="Dim purchase1 As Label";
Debug.ShouldStop(134217728);
_purchase1 = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("purchase1", _purchase1);
 BA.debugLineNum = 125;BA.debugLine="purchase1.Initialize(\"\")";
Debug.ShouldStop(268435456);
_purchase1.runVoidMethod ("Initialize",main.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("")));
 BA.debugLineNum = 126;BA.debugLine="purchase1.Text = totalPur1";
Debug.ShouldStop(536870912);
_purchase1.runMethod(true,"setText",BA.ObjectToCharSequence(_totalpur1));
 BA.debugLineNum = 127;BA.debugLine="purchase1.TextColor = Colors.Black";
Debug.ShouldStop(1073741824);
_purchase1.runMethod(true,"setTextColor",main.mostCurrent.__c.getField(false,"Colors").getField(true,"Black"));
 BA.debugLineNum = 128;BA.debugLine="purchase1.TextSize = primaryFontSize";
Debug.ShouldStop(-2147483648);
_purchase1.runMethod(true,"setTextSize",BA.numberCast(float.class, main._primaryfontsize));
 BA.debugLineNum = 129;BA.debugLine="purchase1.Gravity = Gravity.CENTER";
Debug.ShouldStop(1);
_purchase1.runMethod(true,"setGravity",main.mostCurrent.__c.getField(false,"Gravity").getField(true,"CENTER"));
 BA.debugLineNum = 130;BA.debugLine="purchase1.Typeface = Typeface.SERIF";
Debug.ShouldStop(2);
_purchase1.runMethod(false,"setTypeface",main.mostCurrent.__c.getField(false,"Typeface").getField(false,"SERIF"));
 BA.debugLineNum = 131;BA.debugLine="Panel.AddView(purchase1,0,Panel2.Height+paddin";
Debug.ShouldStop(4);
_panel.runVoidMethod ("AddView",(Object)((_purchase1.getObject())),(Object)(BA.numberCast(int.class, 0)),(Object)(RemoteObject.solve(new RemoteObject[] {main.mostCurrent._panel2.runMethod(true,"getHeight"),_padding}, "+",1, 1)),(Object)(_panelwidth),(Object)(_labelheight));
 BA.debugLineNum = 133;BA.debugLine="Dim purchase1Label As Label";
Debug.ShouldStop(16);
_purchase1label = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("purchase1Label", _purchase1label);
 BA.debugLineNum = 134;BA.debugLine="purchase1Label.Initialize(\"\")";
Debug.ShouldStop(32);
_purchase1label.runVoidMethod ("Initialize",main.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("")));
 BA.debugLineNum = 135;BA.debugLine="purchase1Label.Text = \"First Purchase\"";
Debug.ShouldStop(64);
_purchase1label.runMethod(true,"setText",BA.ObjectToCharSequence("First Purchase"));
 BA.debugLineNum = 136;BA.debugLine="purchase1Label.TextColor = Colors.Gray";
Debug.ShouldStop(128);
_purchase1label.runMethod(true,"setTextColor",main.mostCurrent.__c.getField(false,"Colors").getField(true,"Gray"));
 BA.debugLineNum = 137;BA.debugLine="purchase1Label.TextSize = secondaryFontSize";
Debug.ShouldStop(256);
_purchase1label.runMethod(true,"setTextSize",BA.numberCast(float.class, main._secondaryfontsize));
 BA.debugLineNum = 138;BA.debugLine="purchase1Label.Gravity = Gravity.CENTER";
Debug.ShouldStop(512);
_purchase1label.runMethod(true,"setGravity",main.mostCurrent.__c.getField(false,"Gravity").getField(true,"CENTER"));
 BA.debugLineNum = 139;BA.debugLine="purchase1Label.Typeface = Typeface.MONOSPACE";
Debug.ShouldStop(1024);
_purchase1label.runMethod(false,"setTypeface",main.mostCurrent.__c.getField(false,"Typeface").getField(false,"MONOSPACE"));
 BA.debugLineNum = 140;BA.debugLine="purchase1Label.Text = purchase1Label.Text.ToUp";
Debug.ShouldStop(2048);
_purchase1label.runMethod(true,"setText",BA.ObjectToCharSequence(_purchase1label.runMethod(true,"getText").runMethod(true,"toUpperCase")));
 BA.debugLineNum = 141;BA.debugLine="Panel.AddView(purchase1Label,0,purchase1.top+p";
Debug.ShouldStop(4096);
_panel.runVoidMethod ("AddView",(Object)((_purchase1label.getObject())),(Object)(BA.numberCast(int.class, 0)),(Object)(RemoteObject.solve(new RemoteObject[] {_purchase1.runMethod(true,"getTop"),_padding,main.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 20)))}, "++",2, 1)),(Object)(_panelwidth),(Object)(_labelheight));
 BA.debugLineNum = 143;BA.debugLine="Dim purchase2 As Label";
Debug.ShouldStop(16384);
_purchase2 = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("purchase2", _purchase2);
 BA.debugLineNum = 144;BA.debugLine="purchase2.Initialize(\"\")";
Debug.ShouldStop(32768);
_purchase2.runVoidMethod ("Initialize",main.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("")));
 BA.debugLineNum = 145;BA.debugLine="purchase2.Text = totalPur2";
Debug.ShouldStop(65536);
_purchase2.runMethod(true,"setText",BA.ObjectToCharSequence(_totalpur2));
 BA.debugLineNum = 146;BA.debugLine="purchase2.TextColor = Colors.Black";
Debug.ShouldStop(131072);
_purchase2.runMethod(true,"setTextColor",main.mostCurrent.__c.getField(false,"Colors").getField(true,"Black"));
 BA.debugLineNum = 147;BA.debugLine="purchase2.TextSize = primaryFontSize";
Debug.ShouldStop(262144);
_purchase2.runMethod(true,"setTextSize",BA.numberCast(float.class, main._primaryfontsize));
 BA.debugLineNum = 148;BA.debugLine="purchase2.Gravity = Gravity.CENTER";
Debug.ShouldStop(524288);
_purchase2.runMethod(true,"setGravity",main.mostCurrent.__c.getField(false,"Gravity").getField(true,"CENTER"));
 BA.debugLineNum = 149;BA.debugLine="purchase2.Typeface = Typeface.SERIF";
Debug.ShouldStop(1048576);
_purchase2.runMethod(false,"setTypeface",main.mostCurrent.__c.getField(false,"Typeface").getField(false,"SERIF"));
 BA.debugLineNum = 150;BA.debugLine="Panel.AddView(purchase2,panelWidth,Panel2.Heig";
Debug.ShouldStop(2097152);
_panel.runVoidMethod ("AddView",(Object)((_purchase2.getObject())),(Object)(_panelwidth),(Object)(RemoteObject.solve(new RemoteObject[] {main.mostCurrent._panel2.runMethod(true,"getHeight"),_padding}, "+",1, 1)),(Object)(_panelwidth),(Object)(_labelheight));
 BA.debugLineNum = 152;BA.debugLine="Dim purchase2Label As Label";
Debug.ShouldStop(8388608);
_purchase2label = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("purchase2Label", _purchase2label);
 BA.debugLineNum = 153;BA.debugLine="purchase2Label.Initialize(\"\")";
Debug.ShouldStop(16777216);
_purchase2label.runVoidMethod ("Initialize",main.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("")));
 BA.debugLineNum = 154;BA.debugLine="purchase2Label.Text = \"Second Purchase\"";
Debug.ShouldStop(33554432);
_purchase2label.runMethod(true,"setText",BA.ObjectToCharSequence("Second Purchase"));
 BA.debugLineNum = 155;BA.debugLine="purchase2Label.TextColor = Colors.Gray";
Debug.ShouldStop(67108864);
_purchase2label.runMethod(true,"setTextColor",main.mostCurrent.__c.getField(false,"Colors").getField(true,"Gray"));
 BA.debugLineNum = 156;BA.debugLine="purchase2Label.TextSize = secondaryFontSize";
Debug.ShouldStop(134217728);
_purchase2label.runMethod(true,"setTextSize",BA.numberCast(float.class, main._secondaryfontsize));
 BA.debugLineNum = 157;BA.debugLine="purchase2Label.Gravity = Gravity.CENTER";
Debug.ShouldStop(268435456);
_purchase2label.runMethod(true,"setGravity",main.mostCurrent.__c.getField(false,"Gravity").getField(true,"CENTER"));
 BA.debugLineNum = 158;BA.debugLine="purchase2Label.Typeface = Typeface.MONOSPACE";
Debug.ShouldStop(536870912);
_purchase2label.runMethod(false,"setTypeface",main.mostCurrent.__c.getField(false,"Typeface").getField(false,"MONOSPACE"));
 BA.debugLineNum = 159;BA.debugLine="purchase2Label.Text = purchase2Label.Text.ToUp";
Debug.ShouldStop(1073741824);
_purchase2label.runMethod(true,"setText",BA.ObjectToCharSequence(_purchase2label.runMethod(true,"getText").runMethod(true,"toUpperCase")));
 BA.debugLineNum = 160;BA.debugLine="Panel.AddView(purchase2Label,panelWidth,purcha";
Debug.ShouldStop(-2147483648);
_panel.runVoidMethod ("AddView",(Object)((_purchase2label.getObject())),(Object)(_panelwidth),(Object)(RemoteObject.solve(new RemoteObject[] {_purchase1.runMethod(true,"getTop"),_padding,main.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 20)))}, "++",2, 1)),(Object)(_panelwidth),(Object)(_labelheight));
 BA.debugLineNum = 162;BA.debugLine="Dim purchase3 As Label";
Debug.ShouldStop(2);
_purchase3 = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("purchase3", _purchase3);
 BA.debugLineNum = 163;BA.debugLine="purchase3.Initialize(\"\")";
Debug.ShouldStop(4);
_purchase3.runVoidMethod ("Initialize",main.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("")));
 BA.debugLineNum = 164;BA.debugLine="purchase3.Text = totalPur3";
Debug.ShouldStop(8);
_purchase3.runMethod(true,"setText",BA.ObjectToCharSequence(_totalpur3));
 BA.debugLineNum = 165;BA.debugLine="purchase3.TextColor = Colors.Black";
Debug.ShouldStop(16);
_purchase3.runMethod(true,"setTextColor",main.mostCurrent.__c.getField(false,"Colors").getField(true,"Black"));
 BA.debugLineNum = 166;BA.debugLine="purchase3.TextSize = primaryFontSize";
Debug.ShouldStop(32);
_purchase3.runMethod(true,"setTextSize",BA.numberCast(float.class, main._primaryfontsize));
 BA.debugLineNum = 167;BA.debugLine="purchase3.Gravity = Gravity.CENTER";
Debug.ShouldStop(64);
_purchase3.runMethod(true,"setGravity",main.mostCurrent.__c.getField(false,"Gravity").getField(true,"CENTER"));
 BA.debugLineNum = 168;BA.debugLine="purchase3.Typeface = Typeface.SERIF";
Debug.ShouldStop(128);
_purchase3.runMethod(false,"setTypeface",main.mostCurrent.__c.getField(false,"Typeface").getField(false,"SERIF"));
 BA.debugLineNum = 169;BA.debugLine="Panel.AddView(purchase3,panelWidth*2,Panel2.He";
Debug.ShouldStop(256);
_panel.runVoidMethod ("AddView",(Object)((_purchase3.getObject())),(Object)(RemoteObject.solve(new RemoteObject[] {_panelwidth,RemoteObject.createImmutable(2)}, "*",0, 1)),(Object)(RemoteObject.solve(new RemoteObject[] {main.mostCurrent._panel2.runMethod(true,"getHeight"),_padding}, "+",1, 1)),(Object)(_panelwidth),(Object)(_labelheight));
 BA.debugLineNum = 171;BA.debugLine="Dim purchase3Label As Label";
Debug.ShouldStop(1024);
_purchase3label = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("purchase3Label", _purchase3label);
 BA.debugLineNum = 172;BA.debugLine="purchase3Label.Initialize(\"\")";
Debug.ShouldStop(2048);
_purchase3label.runVoidMethod ("Initialize",main.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("")));
 BA.debugLineNum = 173;BA.debugLine="purchase3Label.Text = \"Third Purchase\"";
Debug.ShouldStop(4096);
_purchase3label.runMethod(true,"setText",BA.ObjectToCharSequence("Third Purchase"));
 BA.debugLineNum = 174;BA.debugLine="purchase3Label.TextColor = Colors.Gray";
Debug.ShouldStop(8192);
_purchase3label.runMethod(true,"setTextColor",main.mostCurrent.__c.getField(false,"Colors").getField(true,"Gray"));
 BA.debugLineNum = 175;BA.debugLine="purchase3Label.TextSize = secondaryFontSize";
Debug.ShouldStop(16384);
_purchase3label.runMethod(true,"setTextSize",BA.numberCast(float.class, main._secondaryfontsize));
 BA.debugLineNum = 176;BA.debugLine="purchase3Label.Gravity = Gravity.CENTER";
Debug.ShouldStop(32768);
_purchase3label.runMethod(true,"setGravity",main.mostCurrent.__c.getField(false,"Gravity").getField(true,"CENTER"));
 BA.debugLineNum = 177;BA.debugLine="purchase3Label.Typeface = Typeface.MONOSPACE";
Debug.ShouldStop(65536);
_purchase3label.runMethod(false,"setTypeface",main.mostCurrent.__c.getField(false,"Typeface").getField(false,"MONOSPACE"));
 BA.debugLineNum = 178;BA.debugLine="purchase3Label.Text = purchase3Label.Text.ToUp";
Debug.ShouldStop(131072);
_purchase3label.runMethod(true,"setText",BA.ObjectToCharSequence(_purchase3label.runMethod(true,"getText").runMethod(true,"toUpperCase")));
 BA.debugLineNum = 179;BA.debugLine="Panel.AddView(purchase3Label,panelWidth*2,purc";
Debug.ShouldStop(262144);
_panel.runVoidMethod ("AddView",(Object)((_purchase3label.getObject())),(Object)(RemoteObject.solve(new RemoteObject[] {_panelwidth,RemoteObject.createImmutable(2)}, "*",0, 1)),(Object)(RemoteObject.solve(new RemoteObject[] {_purchase1.runMethod(true,"getTop"),_padding,main.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 20)))}, "++",2, 1)),(Object)(_panelwidth),(Object)(_labelheight));
 BA.debugLineNum = 181;BA.debugLine="Dim sale1 As Label";
Debug.ShouldStop(1048576);
_sale1 = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("sale1", _sale1);
 BA.debugLineNum = 182;BA.debugLine="sale1.Initialize(\"\")";
Debug.ShouldStop(2097152);
_sale1.runVoidMethod ("Initialize",main.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("")));
 BA.debugLineNum = 183;BA.debugLine="sale1.Text = totalSales1";
Debug.ShouldStop(4194304);
_sale1.runMethod(true,"setText",BA.ObjectToCharSequence(_totalsales1));
 BA.debugLineNum = 184;BA.debugLine="sale1.TextColor = Colors.Black";
Debug.ShouldStop(8388608);
_sale1.runMethod(true,"setTextColor",main.mostCurrent.__c.getField(false,"Colors").getField(true,"Black"));
 BA.debugLineNum = 185;BA.debugLine="sale1.TextSize = primaryFontSize";
Debug.ShouldStop(16777216);
_sale1.runMethod(true,"setTextSize",BA.numberCast(float.class, main._primaryfontsize));
 BA.debugLineNum = 186;BA.debugLine="sale1.Gravity = Gravity.CENTER";
Debug.ShouldStop(33554432);
_sale1.runMethod(true,"setGravity",main.mostCurrent.__c.getField(false,"Gravity").getField(true,"CENTER"));
 BA.debugLineNum = 187;BA.debugLine="sale1.Typeface = Typeface.SERIF";
Debug.ShouldStop(67108864);
_sale1.runMethod(false,"setTypeface",main.mostCurrent.__c.getField(false,"Typeface").getField(false,"SERIF"));
 BA.debugLineNum = 188;BA.debugLine="Panel.AddView(sale1,0,purchase3Label.Height+pa";
Debug.ShouldStop(134217728);
_panel.runVoidMethod ("AddView",(Object)((_sale1.getObject())),(Object)(BA.numberCast(int.class, 0)),(Object)(RemoteObject.solve(new RemoteObject[] {_purchase3label.runMethod(true,"getHeight"),_padding,main.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 90)))}, "++",2, 1)),(Object)(_panelwidth),(Object)(_labelheight));
 BA.debugLineNum = 190;BA.debugLine="Dim sale1Label As Label";
Debug.ShouldStop(536870912);
_sale1label = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("sale1Label", _sale1label);
 BA.debugLineNum = 191;BA.debugLine="sale1Label.Initialize(\"\")";
Debug.ShouldStop(1073741824);
_sale1label.runVoidMethod ("Initialize",main.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("")));
 BA.debugLineNum = 192;BA.debugLine="sale1Label.Text = \"First Sale\"";
Debug.ShouldStop(-2147483648);
_sale1label.runMethod(true,"setText",BA.ObjectToCharSequence("First Sale"));
 BA.debugLineNum = 193;BA.debugLine="sale1Label.TextColor = Colors.Gray";
Debug.ShouldStop(1);
_sale1label.runMethod(true,"setTextColor",main.mostCurrent.__c.getField(false,"Colors").getField(true,"Gray"));
 BA.debugLineNum = 194;BA.debugLine="sale1Label.TextSize = secondaryFontSize";
Debug.ShouldStop(2);
_sale1label.runMethod(true,"setTextSize",BA.numberCast(float.class, main._secondaryfontsize));
 BA.debugLineNum = 195;BA.debugLine="sale1Label.Gravity = Gravity.CENTER";
Debug.ShouldStop(4);
_sale1label.runMethod(true,"setGravity",main.mostCurrent.__c.getField(false,"Gravity").getField(true,"CENTER"));
 BA.debugLineNum = 196;BA.debugLine="sale1Label.Typeface = Typeface.MONOSPACE";
Debug.ShouldStop(8);
_sale1label.runMethod(false,"setTypeface",main.mostCurrent.__c.getField(false,"Typeface").getField(false,"MONOSPACE"));
 BA.debugLineNum = 197;BA.debugLine="sale1Label.Text = sale1Label.Text.ToUpperCase";
Debug.ShouldStop(16);
_sale1label.runMethod(true,"setText",BA.ObjectToCharSequence(_sale1label.runMethod(true,"getText").runMethod(true,"toUpperCase")));
 BA.debugLineNum = 198;BA.debugLine="Panel.AddView(sale1Label,0,sale1.top+padding+2";
Debug.ShouldStop(32);
_panel.runVoidMethod ("AddView",(Object)((_sale1label.getObject())),(Object)(BA.numberCast(int.class, 0)),(Object)(RemoteObject.solve(new RemoteObject[] {_sale1.runMethod(true,"getTop"),_padding,main.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 20)))}, "++",2, 1)),(Object)(_panelwidth),(Object)(_labelheight));
 BA.debugLineNum = 200;BA.debugLine="Dim sale2 As Label";
Debug.ShouldStop(128);
_sale2 = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("sale2", _sale2);
 BA.debugLineNum = 201;BA.debugLine="sale2.Initialize(\"\")";
Debug.ShouldStop(256);
_sale2.runVoidMethod ("Initialize",main.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("")));
 BA.debugLineNum = 202;BA.debugLine="sale2.Text = totalSales2";
Debug.ShouldStop(512);
_sale2.runMethod(true,"setText",BA.ObjectToCharSequence(_totalsales2));
 BA.debugLineNum = 203;BA.debugLine="sale2.TextColor = Colors.Black";
Debug.ShouldStop(1024);
_sale2.runMethod(true,"setTextColor",main.mostCurrent.__c.getField(false,"Colors").getField(true,"Black"));
 BA.debugLineNum = 204;BA.debugLine="sale2.TextSize = primaryFontSize";
Debug.ShouldStop(2048);
_sale2.runMethod(true,"setTextSize",BA.numberCast(float.class, main._primaryfontsize));
 BA.debugLineNum = 205;BA.debugLine="sale2.Gravity = Gravity.CENTER";
Debug.ShouldStop(4096);
_sale2.runMethod(true,"setGravity",main.mostCurrent.__c.getField(false,"Gravity").getField(true,"CENTER"));
 BA.debugLineNum = 206;BA.debugLine="sale2.Typeface = Typeface.SERIF";
Debug.ShouldStop(8192);
_sale2.runMethod(false,"setTypeface",main.mostCurrent.__c.getField(false,"Typeface").getField(false,"SERIF"));
 BA.debugLineNum = 207;BA.debugLine="Panel.AddView(sale2,panelWidth,purchase3Label.";
Debug.ShouldStop(16384);
_panel.runVoidMethod ("AddView",(Object)((_sale2.getObject())),(Object)(_panelwidth),(Object)(RemoteObject.solve(new RemoteObject[] {_purchase3label.runMethod(true,"getHeight"),_padding,main.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 90)))}, "++",2, 1)),(Object)(_panelwidth),(Object)(_labelheight));
 BA.debugLineNum = 209;BA.debugLine="Dim sale2Label As Label";
Debug.ShouldStop(65536);
_sale2label = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("sale2Label", _sale2label);
 BA.debugLineNum = 210;BA.debugLine="sale2Label.Initialize(\"\")";
Debug.ShouldStop(131072);
_sale2label.runVoidMethod ("Initialize",main.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("")));
 BA.debugLineNum = 211;BA.debugLine="sale2Label.Text = \" Second Sale\"";
Debug.ShouldStop(262144);
_sale2label.runMethod(true,"setText",BA.ObjectToCharSequence(" Second Sale"));
 BA.debugLineNum = 212;BA.debugLine="sale2Label.TextColor = Colors.Gray";
Debug.ShouldStop(524288);
_sale2label.runMethod(true,"setTextColor",main.mostCurrent.__c.getField(false,"Colors").getField(true,"Gray"));
 BA.debugLineNum = 213;BA.debugLine="sale2Label.TextSize = secondaryFontSize";
Debug.ShouldStop(1048576);
_sale2label.runMethod(true,"setTextSize",BA.numberCast(float.class, main._secondaryfontsize));
 BA.debugLineNum = 214;BA.debugLine="sale2Label.Gravity = Gravity.CENTER";
Debug.ShouldStop(2097152);
_sale2label.runMethod(true,"setGravity",main.mostCurrent.__c.getField(false,"Gravity").getField(true,"CENTER"));
 BA.debugLineNum = 215;BA.debugLine="sale2Label.Typeface = Typeface.MONOSPACE";
Debug.ShouldStop(4194304);
_sale2label.runMethod(false,"setTypeface",main.mostCurrent.__c.getField(false,"Typeface").getField(false,"MONOSPACE"));
 BA.debugLineNum = 216;BA.debugLine="sale2Label.Text = sale2Label.Text.ToUpperCase";
Debug.ShouldStop(8388608);
_sale2label.runMethod(true,"setText",BA.ObjectToCharSequence(_sale2label.runMethod(true,"getText").runMethod(true,"toUpperCase")));
 BA.debugLineNum = 217;BA.debugLine="Panel.AddView(sale2Label,panelWidth,sale2.top+";
Debug.ShouldStop(16777216);
_panel.runVoidMethod ("AddView",(Object)((_sale2label.getObject())),(Object)(_panelwidth),(Object)(RemoteObject.solve(new RemoteObject[] {_sale2.runMethod(true,"getTop"),_padding,main.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 20)))}, "++",2, 1)),(Object)(_panelwidth),(Object)(_labelheight));
 BA.debugLineNum = 219;BA.debugLine="Dim sale3 As Label";
Debug.ShouldStop(67108864);
_sale3 = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("sale3", _sale3);
 BA.debugLineNum = 220;BA.debugLine="sale3.Initialize(\"\")";
Debug.ShouldStop(134217728);
_sale3.runVoidMethod ("Initialize",main.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("")));
 BA.debugLineNum = 221;BA.debugLine="sale3.Text = totalSales3";
Debug.ShouldStop(268435456);
_sale3.runMethod(true,"setText",BA.ObjectToCharSequence(_totalsales3));
 BA.debugLineNum = 222;BA.debugLine="sale3.TextColor = Colors.Black";
Debug.ShouldStop(536870912);
_sale3.runMethod(true,"setTextColor",main.mostCurrent.__c.getField(false,"Colors").getField(true,"Black"));
 BA.debugLineNum = 223;BA.debugLine="sale3.TextSize = primaryFontSize";
Debug.ShouldStop(1073741824);
_sale3.runMethod(true,"setTextSize",BA.numberCast(float.class, main._primaryfontsize));
 BA.debugLineNum = 224;BA.debugLine="sale3.Gravity = Gravity.CENTER";
Debug.ShouldStop(-2147483648);
_sale3.runMethod(true,"setGravity",main.mostCurrent.__c.getField(false,"Gravity").getField(true,"CENTER"));
 BA.debugLineNum = 225;BA.debugLine="sale3.Typeface = Typeface.SERIF";
Debug.ShouldStop(1);
_sale3.runMethod(false,"setTypeface",main.mostCurrent.__c.getField(false,"Typeface").getField(false,"SERIF"));
 BA.debugLineNum = 226;BA.debugLine="Panel.AddView(sale3,panelWidth*2,sale2Label.He";
Debug.ShouldStop(2);
_panel.runVoidMethod ("AddView",(Object)((_sale3.getObject())),(Object)(RemoteObject.solve(new RemoteObject[] {_panelwidth,RemoteObject.createImmutable(2)}, "*",0, 1)),(Object)(RemoteObject.solve(new RemoteObject[] {_sale2label.runMethod(true,"getHeight"),_padding,main.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 90)))}, "++",2, 1)),(Object)(_panelwidth),(Object)(_labelheight));
 BA.debugLineNum = 228;BA.debugLine="Dim sale3Label As Label";
Debug.ShouldStop(8);
_sale3label = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("sale3Label", _sale3label);
 BA.debugLineNum = 229;BA.debugLine="sale3Label.Initialize(\"\")";
Debug.ShouldStop(16);
_sale3label.runVoidMethod ("Initialize",main.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("")));
 BA.debugLineNum = 230;BA.debugLine="sale3Label.Text = \" Third Sale\"";
Debug.ShouldStop(32);
_sale3label.runMethod(true,"setText",BA.ObjectToCharSequence(" Third Sale"));
 BA.debugLineNum = 231;BA.debugLine="sale3Label.TextColor = Colors.Gray";
Debug.ShouldStop(64);
_sale3label.runMethod(true,"setTextColor",main.mostCurrent.__c.getField(false,"Colors").getField(true,"Gray"));
 BA.debugLineNum = 232;BA.debugLine="sale3Label.TextSize = secondaryFontSize";
Debug.ShouldStop(128);
_sale3label.runMethod(true,"setTextSize",BA.numberCast(float.class, main._secondaryfontsize));
 BA.debugLineNum = 233;BA.debugLine="sale3Label.Gravity = Gravity.CENTER";
Debug.ShouldStop(256);
_sale3label.runMethod(true,"setGravity",main.mostCurrent.__c.getField(false,"Gravity").getField(true,"CENTER"));
 BA.debugLineNum = 234;BA.debugLine="sale3Label.Typeface = Typeface.MONOSPACE";
Debug.ShouldStop(512);
_sale3label.runMethod(false,"setTypeface",main.mostCurrent.__c.getField(false,"Typeface").getField(false,"MONOSPACE"));
 BA.debugLineNum = 235;BA.debugLine="sale3Label.Text = sale3Label.Text.ToUpperCase";
Debug.ShouldStop(1024);
_sale3label.runMethod(true,"setText",BA.ObjectToCharSequence(_sale3label.runMethod(true,"getText").runMethod(true,"toUpperCase")));
 BA.debugLineNum = 236;BA.debugLine="Panel.AddView(sale3Label,panelWidth*2,sale1.to";
Debug.ShouldStop(2048);
_panel.runVoidMethod ("AddView",(Object)((_sale3label.getObject())),(Object)(RemoteObject.solve(new RemoteObject[] {_panelwidth,RemoteObject.createImmutable(2)}, "*",0, 1)),(Object)(RemoteObject.solve(new RemoteObject[] {_sale1.runMethod(true,"getTop"),_padding,main.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 20)))}, "++",2, 1)),(Object)(_panelwidth),(Object)(_labelheight));
 BA.debugLineNum = 238;BA.debugLine="panelWidth = Panel.Width /2";
Debug.ShouldStop(8192);
_panelwidth = BA.numberCast(int.class, RemoteObject.solve(new RemoteObject[] {_panel.runMethod(true,"getWidth"),RemoteObject.createImmutable(2)}, "/",0, 0));Debug.locals.put("panelWidth", _panelwidth);
 BA.debugLineNum = 240;BA.debugLine="Dim totalStore As Label";
Debug.ShouldStop(32768);
_totalstore = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("totalStore", _totalstore);
 BA.debugLineNum = 241;BA.debugLine="totalStore.Initialize(\"\")";
Debug.ShouldStop(65536);
_totalstore.runVoidMethod ("Initialize",main.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("")));
 BA.debugLineNum = 242;BA.debugLine="totalStore.Text = total_count";
Debug.ShouldStop(131072);
_totalstore.runMethod(true,"setText",BA.ObjectToCharSequence(_total_count));
 BA.debugLineNum = 243;BA.debugLine="totalStore.TextColor = Colors.Black";
Debug.ShouldStop(262144);
_totalstore.runMethod(true,"setTextColor",main.mostCurrent.__c.getField(false,"Colors").getField(true,"Black"));
 BA.debugLineNum = 244;BA.debugLine="totalStore.TextSize = primaryFontSize";
Debug.ShouldStop(524288);
_totalstore.runMethod(true,"setTextSize",BA.numberCast(float.class, main._primaryfontsize));
 BA.debugLineNum = 245;BA.debugLine="totalStore.Gravity = Gravity.CENTER";
Debug.ShouldStop(1048576);
_totalstore.runMethod(true,"setGravity",main.mostCurrent.__c.getField(false,"Gravity").getField(true,"CENTER"));
 BA.debugLineNum = 246;BA.debugLine="totalStore.Typeface = Typeface.SERIF";
Debug.ShouldStop(2097152);
_totalstore.runMethod(false,"setTypeface",main.mostCurrent.__c.getField(false,"Typeface").getField(false,"SERIF"));
 BA.debugLineNum = 247;BA.debugLine="Panel.AddView(totalStore,0,sale3Label.Height+p";
Debug.ShouldStop(4194304);
_panel.runVoidMethod ("AddView",(Object)((_totalstore.getObject())),(Object)(BA.numberCast(int.class, 0)),(Object)(RemoteObject.solve(new RemoteObject[] {_sale3label.runMethod(true,"getHeight"),_padding,main.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 160)))}, "++",2, 1)),(Object)(_panelwidth),(Object)(_labelheight));
 BA.debugLineNum = 249;BA.debugLine="Dim totalStoreLabel As Label";
Debug.ShouldStop(16777216);
_totalstorelabel = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("totalStoreLabel", _totalstorelabel);
 BA.debugLineNum = 250;BA.debugLine="totalStoreLabel.Initialize(\"\")";
Debug.ShouldStop(33554432);
_totalstorelabel.runVoidMethod ("Initialize",main.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("")));
 BA.debugLineNum = 251;BA.debugLine="totalStoreLabel.Text = \" Total Store\"";
Debug.ShouldStop(67108864);
_totalstorelabel.runMethod(true,"setText",BA.ObjectToCharSequence(" Total Store"));
 BA.debugLineNum = 252;BA.debugLine="totalStoreLabel.TextColor = Colors.Gray";
Debug.ShouldStop(134217728);
_totalstorelabel.runMethod(true,"setTextColor",main.mostCurrent.__c.getField(false,"Colors").getField(true,"Gray"));
 BA.debugLineNum = 253;BA.debugLine="totalStoreLabel.TextSize = secondaryFontSize";
Debug.ShouldStop(268435456);
_totalstorelabel.runMethod(true,"setTextSize",BA.numberCast(float.class, main._secondaryfontsize));
 BA.debugLineNum = 254;BA.debugLine="totalStoreLabel.Gravity = Gravity.CENTER";
Debug.ShouldStop(536870912);
_totalstorelabel.runMethod(true,"setGravity",main.mostCurrent.__c.getField(false,"Gravity").getField(true,"CENTER"));
 BA.debugLineNum = 255;BA.debugLine="totalStoreLabel.Typeface = Typeface.MONOSPACE";
Debug.ShouldStop(1073741824);
_totalstorelabel.runMethod(false,"setTypeface",main.mostCurrent.__c.getField(false,"Typeface").getField(false,"MONOSPACE"));
 BA.debugLineNum = 256;BA.debugLine="totalStoreLabel.Text = totalStoreLabel.Text.To";
Debug.ShouldStop(-2147483648);
_totalstorelabel.runMethod(true,"setText",BA.ObjectToCharSequence(_totalstorelabel.runMethod(true,"getText").runMethod(true,"toUpperCase")));
 BA.debugLineNum = 257;BA.debugLine="Panel.AddView(totalStoreLabel,0,totalStore.top";
Debug.ShouldStop(1);
_panel.runVoidMethod ("AddView",(Object)((_totalstorelabel.getObject())),(Object)(BA.numberCast(int.class, 0)),(Object)(RemoteObject.solve(new RemoteObject[] {_totalstore.runMethod(true,"getTop"),_padding,main.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 20)))}, "++",2, 1)),(Object)(_panelwidth),(Object)(_labelheight));
 BA.debugLineNum = 259;BA.debugLine="Dim totalPos As Label";
Debug.ShouldStop(4);
_totalpos = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("totalPos", _totalpos);
 BA.debugLineNum = 260;BA.debugLine="totalPos.Initialize(\"\")";
Debug.ShouldStop(8);
_totalpos.runVoidMethod ("Initialize",main.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("")));
 BA.debugLineNum = 261;BA.debugLine="totalPos.Text = total_pos";
Debug.ShouldStop(16);
_totalpos.runMethod(true,"setText",BA.ObjectToCharSequence(_total_pos));
 BA.debugLineNum = 262;BA.debugLine="totalPos.TextColor = Colors.Black";
Debug.ShouldStop(32);
_totalpos.runMethod(true,"setTextColor",main.mostCurrent.__c.getField(false,"Colors").getField(true,"Black"));
 BA.debugLineNum = 263;BA.debugLine="totalPos.TextSize = primaryFontSize";
Debug.ShouldStop(64);
_totalpos.runMethod(true,"setTextSize",BA.numberCast(float.class, main._primaryfontsize));
 BA.debugLineNum = 264;BA.debugLine="totalPos.Gravity = Gravity.CENTER";
Debug.ShouldStop(128);
_totalpos.runMethod(true,"setGravity",main.mostCurrent.__c.getField(false,"Gravity").getField(true,"CENTER"));
 BA.debugLineNum = 265;BA.debugLine="totalPos.Typeface = Typeface.SERIF";
Debug.ShouldStop(256);
_totalpos.runMethod(false,"setTypeface",main.mostCurrent.__c.getField(false,"Typeface").getField(false,"SERIF"));
 BA.debugLineNum = 266;BA.debugLine="Panel.AddView(totalPos,panelWidth,totalStoreLa";
Debug.ShouldStop(512);
_panel.runVoidMethod ("AddView",(Object)((_totalpos.getObject())),(Object)(_panelwidth),(Object)(RemoteObject.solve(new RemoteObject[] {_totalstorelabel.runMethod(true,"getHeight"),_padding,main.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 160)))}, "++",2, 1)),(Object)(_panelwidth),(Object)(_labelheight));
 BA.debugLineNum = 268;BA.debugLine="Dim totalPosLabel As Label";
Debug.ShouldStop(2048);
_totalposlabel = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("totalPosLabel", _totalposlabel);
 BA.debugLineNum = 269;BA.debugLine="totalPosLabel.Initialize(\"\")";
Debug.ShouldStop(4096);
_totalposlabel.runVoidMethod ("Initialize",main.mostCurrent.activityBA,(Object)(RemoteObject.createImmutable("")));
 BA.debugLineNum = 270;BA.debugLine="totalPosLabel.Text = \" Total Pos\"";
Debug.ShouldStop(8192);
_totalposlabel.runMethod(true,"setText",BA.ObjectToCharSequence(" Total Pos"));
 BA.debugLineNum = 271;BA.debugLine="totalPosLabel.TextColor = Colors.Gray";
Debug.ShouldStop(16384);
_totalposlabel.runMethod(true,"setTextColor",main.mostCurrent.__c.getField(false,"Colors").getField(true,"Gray"));
 BA.debugLineNum = 272;BA.debugLine="totalPosLabel.TextSize = secondaryFontSize";
Debug.ShouldStop(32768);
_totalposlabel.runMethod(true,"setTextSize",BA.numberCast(float.class, main._secondaryfontsize));
 BA.debugLineNum = 273;BA.debugLine="totalPosLabel.Gravity = Gravity.CENTER";
Debug.ShouldStop(65536);
_totalposlabel.runMethod(true,"setGravity",main.mostCurrent.__c.getField(false,"Gravity").getField(true,"CENTER"));
 BA.debugLineNum = 274;BA.debugLine="totalPosLabel.Typeface = Typeface.MONOSPACE";
Debug.ShouldStop(131072);
_totalposlabel.runMethod(false,"setTypeface",main.mostCurrent.__c.getField(false,"Typeface").getField(false,"MONOSPACE"));
 BA.debugLineNum = 275;BA.debugLine="totalPosLabel.Text = totalPosLabel.Text.ToUppe";
Debug.ShouldStop(262144);
_totalposlabel.runMethod(true,"setText",BA.ObjectToCharSequence(_totalposlabel.runMethod(true,"getText").runMethod(true,"toUpperCase")));
 BA.debugLineNum = 276;BA.debugLine="Panel.AddView(totalPosLabel,panelWidth,totalPo";
Debug.ShouldStop(524288);
_panel.runVoidMethod ("AddView",(Object)((_totalposlabel.getObject())),(Object)(_panelwidth),(Object)(RemoteObject.solve(new RemoteObject[] {_totalpos.runMethod(true,"getTop"),_padding,main.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 20)))}, "++",2, 1)),(Object)(_panelwidth),(Object)(_labelheight));
 BA.debugLineNum = 280;BA.debugLine="If Activity.Width >= 1340 Then";
Debug.ShouldStop(8388608);
if (RemoteObject.solveBoolean("g",main.mostCurrent._activity.runMethod(true,"getWidth"),BA.numberCast(double.class, 1340))) { 
 BA.debugLineNum = 281;BA.debugLine="count = count + 1";
Debug.ShouldStop(16777216);
_count = RemoteObject.solve(new RemoteObject[] {_count,RemoteObject.createImmutable(1)}, "+",1, 1);Debug.locals.put("count", _count);
 BA.debugLineNum = 282;BA.debugLine="If count Mod numColumns = 0 Then";
Debug.ShouldStop(33554432);
if (RemoteObject.solveBoolean("=",RemoteObject.solve(new RemoteObject[] {_count,_numcolumns}, "%",0, 1),BA.numberCast(double.class, 0))) { 
 BA.debugLineNum = 284;BA.debugLine="leftPosition = 10dip";
Debug.ShouldStop(134217728);
_leftposition = main.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 10)));Debug.locals.put("leftPosition", _leftposition);
 BA.debugLineNum = 285;BA.debugLine="topPosition = topPosition + pnlHeight + padd";
Debug.ShouldStop(268435456);
_topposition = RemoteObject.solve(new RemoteObject[] {_topposition,_pnlheight,_padding}, "++",2, 1);Debug.locals.put("topPosition", _topposition);
 }else {
 BA.debugLineNum = 288;BA.debugLine="leftPosition = leftPosition + pnlWidth + pad";
Debug.ShouldStop(-2147483648);
_leftposition = RemoteObject.solve(new RemoteObject[] {_leftposition,_pnlwidth,_padding}, "++",2, 1);Debug.locals.put("leftPosition", _leftposition);
 };
 BA.debugLineNum = 290;BA.debugLine="scrollHeight = scrollHeight + 175dip";
Debug.ShouldStop(2);
_scrollheight = RemoteObject.solve(new RemoteObject[] {_scrollheight,main.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 175)))}, "+",1, 1);Debug.locals.put("scrollHeight", _scrollheight);
 }else {
 BA.debugLineNum = 292;BA.debugLine="topPosition = topPosition + pnlHeight + paddi";
Debug.ShouldStop(8);
_topposition = RemoteObject.solve(new RemoteObject[] {_topposition,_pnlheight,_padding}, "++",2, 1);Debug.locals.put("topPosition", _topposition);
 BA.debugLineNum = 293;BA.debugLine="scrollHeight = scrollHeight + 300dip + paddin";
Debug.ShouldStop(16);
_scrollheight = RemoteObject.solve(new RemoteObject[] {_scrollheight,main.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 300))),_padding}, "++",2, 1);Debug.locals.put("scrollHeight", _scrollheight);
 };
 BA.debugLineNum = 297;BA.debugLine="Dim cd As ColorDrawable";
Debug.ShouldStop(256);
_cd = RemoteObject.createNew ("anywheresoftware.b4a.objects.drawable.ColorDrawable");Debug.locals.put("cd", _cd);
 BA.debugLineNum = 298;BA.debugLine="cd.Initialize2(Colors.White, 0dip, 1dip, Color";
Debug.ShouldStop(512);
_cd.runVoidMethod ("Initialize2",(Object)(main.mostCurrent.__c.getField(false,"Colors").getField(true,"White")),(Object)(main.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 0)))),(Object)(main.mostCurrent.__c.runMethod(true,"DipToCurrent",(Object)(BA.numberCast(int.class, 1)))),(Object)(main.mostCurrent.__c.getField(false,"Colors").getField(true,"Black")));
 BA.debugLineNum = 299;BA.debugLine="Panel.Background = cd";
Debug.ShouldStop(1024);
_panel.runMethod(false,"setBackground",(_cd.getObject()));
 }
}Debug.locals.put("record", _record);
;
 BA.debugLineNum = 303;BA.debugLine="ScrollView1.Panel.Height = scrollHeight";
Debug.ShouldStop(16384);
main.mostCurrent._scrollview1.runMethod(false,"getPanel").runMethod(true,"setHeight",_scrollheight);
 Debug.CheckDeviceExceptions();
} 
       catch (Exception e221) {
			BA.rdebugUtils.runVoidMethod("setLastException",main.processBA, e221.toString()); BA.debugLineNum = 306;BA.debugLine="ToastMessageShow(\"Error parsing data\", True)";
Debug.ShouldStop(131072);
main.mostCurrent.__c.runVoidMethod ("ToastMessageShow",(Object)(BA.ObjectToCharSequence("Error parsing data")),(Object)(main.mostCurrent.__c.getField(true,"True")));
 };
 }else {
 BA.debugLineNum = 309;BA.debugLine="ToastMessageShow(\"Error: \" & job.ErrorMessage, T";
Debug.ShouldStop(1048576);
main.mostCurrent.__c.runVoidMethod ("ToastMessageShow",(Object)(BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable("Error: "),_job.getField(true,"_errormessage" /*RemoteObject*/ )))),(Object)(main.mostCurrent.__c.getField(true,"True")));
 };
 BA.debugLineNum = 312;BA.debugLine="job.Release";
Debug.ShouldStop(8388608);
_job.runClassMethod (b4a.example.httpjob.class, "_release" /*RemoteObject*/ );
 BA.debugLineNum = 313;BA.debugLine="End Sub";
Debug.ShouldStop(16777216);
return RemoteObject.createImmutable("");
}
catch (Exception e) {
			throw Debug.ErrorCaught(e);
		} 
finally {
			Debug.PopSubsStack();
		}}
public static RemoteObject  _label17_click() throws Exception{
try {
		Debug.PushSubsStack("Label17_Click (main) ","main",0,main.mostCurrent.activityBA,main.mostCurrent,351);
if (RapidSub.canDelegate("label17_click")) { return b4a.example.main.remoteMe.runUserSub(false, "main","label17_click");}
RemoteObject _clickedlabel = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _selectedcompany = RemoteObject.createImmutable("");
 BA.debugLineNum = 351;BA.debugLine="Private Sub Label17_Click";
Debug.ShouldStop(1073741824);
 BA.debugLineNum = 352;BA.debugLine="Dim clickedLabel As Label = Sender ' Get the clic";
Debug.ShouldStop(-2147483648);
_clickedlabel = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");
_clickedlabel = RemoteObject.declareNull("anywheresoftware.b4a.AbsObjectWrapper").runMethod(false, "ConvertToWrapper", RemoteObject.createNew("anywheresoftware.b4a.objects.LabelWrapper"), main.mostCurrent.__c.runMethod(false,"Sender",main.mostCurrent.activityBA));Debug.locals.put("clickedLabel", _clickedlabel);Debug.locals.put("clickedLabel", _clickedlabel);
 BA.debugLineNum = 353;BA.debugLine="Dim selectedCompany As String = clickedLabel.Tag";
Debug.ShouldStop(1);
_selectedcompany = BA.ObjectToString(_clickedlabel.runMethod(false,"getTag"));Debug.locals.put("selectedCompany", _selectedcompany);Debug.locals.put("selectedCompany", _selectedcompany);
 BA.debugLineNum = 355;BA.debugLine="Starter.company_selected = selectedCompany";
Debug.ShouldStop(4);
main.mostCurrent._starter._company_selected /*RemoteObject*/  = _selectedcompany;
 BA.debugLineNum = 358;BA.debugLine="StartActivity(\"Branch\")";
Debug.ShouldStop(32);
main.mostCurrent.__c.runVoidMethod ("StartActivity",main.processBA,(Object)((RemoteObject.createImmutable("Branch"))));
 BA.debugLineNum = 359;BA.debugLine="End Sub";
Debug.ShouldStop(64);
return RemoteObject.createImmutable("");
}
catch (Exception e) {
			throw Debug.ErrorCaught(e);
		} 
finally {
			Debug.PopSubsStack();
		}}
public static RemoteObject  _loadcompanydata() throws Exception{
try {
		Debug.PushSubsStack("LoadCompanyData (main) ","main",0,main.mostCurrent.activityBA,main.mostCurrent,40);
if (RapidSub.canDelegate("loadcompanydata")) { return b4a.example.main.remoteMe.runUserSub(false, "main","loadcompanydata");}
RemoteObject _job1 = RemoteObject.declareNull("b4a.example.httpjob");
 BA.debugLineNum = 40;BA.debugLine="Sub LoadCompanyData";
Debug.ShouldStop(128);
 BA.debugLineNum = 41;BA.debugLine="Dim Job1 As HttpJob";
Debug.ShouldStop(256);
_job1 = RemoteObject.createNew ("b4a.example.httpjob");Debug.locals.put("Job1", _job1);
 BA.debugLineNum = 42;BA.debugLine="Job1.Initialize(\"LoadData\", Me)";
Debug.ShouldStop(512);
_job1.runClassMethod (b4a.example.httpjob.class, "_initialize" /*RemoteObject*/ ,main.processBA,(Object)(BA.ObjectToString("LoadData")),(Object)(main.getObject()));
 BA.debugLineNum = 43;BA.debugLine="Job1.Download(PHPURL)";
Debug.ShouldStop(1024);
_job1.runClassMethod (b4a.example.httpjob.class, "_download" /*RemoteObject*/ ,(Object)(main.mostCurrent._phpurl));
 BA.debugLineNum = 44;BA.debugLine="ProgressDialogShow(\"Loading Data...\")";
Debug.ShouldStop(2048);
main.mostCurrent.__c.runVoidMethod ("ProgressDialogShow",main.mostCurrent.activityBA,(Object)(BA.ObjectToCharSequence(RemoteObject.createImmutable("Loading Data..."))));
 BA.debugLineNum = 45;BA.debugLine="End Sub";
Debug.ShouldStop(4096);
return RemoteObject.createImmutable("");
}
catch (Exception e) {
			throw Debug.ErrorCaught(e);
		} 
finally {
			Debug.PopSubsStack();
		}}

public static void initializeProcessGlobals() {
    
    if (main.processGlobalsRun == false) {
	    main.processGlobalsRun = true;
		try {
		        main_subs_0._process_globals();
starter_subs_0._process_globals();
branch_subs_0._process_globals();
device_subs_0._process_globals();
httputils2service_subs_0._process_globals();
main.myClass = BA.getDeviceClass ("b4a.example.main");
starter.myClass = BA.getDeviceClass ("b4a.example.starter");
branch.myClass = BA.getDeviceClass ("b4a.example.branch");
device.myClass = BA.getDeviceClass ("b4a.example.device");
bargraph.myClass = BA.getDeviceClass ("b4a.example.bargraph");
httputils2service.myClass = BA.getDeviceClass ("b4a.example.httputils2service");
httpjob.myClass = BA.getDeviceClass ("b4a.example.httpjob");
		
        } catch (Exception e) {
			throw new RuntimeException(e);
		}
    }
}public static RemoteObject  _process_globals() throws Exception{
 //BA.debugLineNum = 15;BA.debugLine="Sub Process_Globals";
 //BA.debugLineNum = 18;BA.debugLine="Private xui As XUI";
main._xui = RemoteObject.createNew ("anywheresoftware.b4a.objects.B4XViewWrapper.XUI");
 //BA.debugLineNum = 19;BA.debugLine="Public company As String";
main._company = RemoteObject.createImmutable("");
 //BA.debugLineNum = 20;BA.debugLine="End Sub";
return RemoteObject.createImmutable("");
}
}